#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Week4.Resource", IsApplication=true)]

namespace Week4
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int antelope = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bear = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int black_checker = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int black_checker_small = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int dolphin = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int gibbon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int kamodo_dragon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int monoandroidsplash = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int red_checker = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int red_checker_small = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int reef_shark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int tamarin = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int tiger_shark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int wolverine = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int animalImage = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int animalName = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int checkerBoardGrid = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int checkerboardGrid = 2131099648;
			
			// aapt resource value: 0x7f06000f
			public const int eight = 2131099663;
			
			// aapt resource value: 0x7f060019
			public const int eightteen = 2131099673;
			
			// aapt resource value: 0x7f060012
			public const int eleven = 2131099666;
			
			// aapt resource value: 0x7f060046
			public const int faceToggle = 2131099718;
			
			// aapt resource value: 0x7f060016
			public const int fifteen = 2131099670;
			
			// aapt resource value: 0x7f060039
			public const int fifty = 2131099705;
			
			// aapt resource value: 0x7f060043
			public const int fiftyeight = 2131099715;
			
			// aapt resource value: 0x7f06003e
			public const int fiftyfive = 2131099710;
			
			// aapt resource value: 0x7f06003d
			public const int fiftyfour = 2131099709;
			
			// aapt resource value: 0x7f060044
			public const int fiftynine = 2131099716;
			
			// aapt resource value: 0x7f06003a
			public const int fiftyone = 2131099706;
			
			// aapt resource value: 0x7f060042
			public const int fiftyseven = 2131099714;
			
			// aapt resource value: 0x7f06003f
			public const int fiftysix = 2131099711;
			
			// aapt resource value: 0x7f06003c
			public const int fiftythree = 2131099708;
			
			// aapt resource value: 0x7f06003b
			public const int fiftytwo = 2131099707;
			
			// aapt resource value: 0x7f06000c
			public const int five = 2131099660;
			
			// aapt resource value: 0x7f06002f
			public const int forty = 2131099695;
			
			// aapt resource value: 0x7f060037
			public const int fortyeight = 2131099703;
			
			// aapt resource value: 0x7f060034
			public const int fortyfive = 2131099700;
			
			// aapt resource value: 0x7f060033
			public const int fortyfour = 2131099699;
			
			// aapt resource value: 0x7f060038
			public const int fortynine = 2131099704;
			
			// aapt resource value: 0x7f060030
			public const int fortyone = 2131099696;
			
			// aapt resource value: 0x7f060036
			public const int fortyseven = 2131099702;
			
			// aapt resource value: 0x7f060035
			public const int fortysix = 2131099701;
			
			// aapt resource value: 0x7f060032
			public const int fortythree = 2131099698;
			
			// aapt resource value: 0x7f060031
			public const int fortytwo = 2131099697;
			
			// aapt resource value: 0x7f06000b
			public const int four = 2131099659;
			
			// aapt resource value: 0x7f060015
			public const int fourteen = 2131099669;
			
			// aapt resource value: 0x7f060002
			public const int minnesotaZoo = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int minnesotaZooListView = 2131099654;
			
			// aapt resource value: 0x7f060010
			public const int nine = 2131099664;
			
			// aapt resource value: 0x7f06001a
			public const int nineteen = 2131099674;
			
			// aapt resource value: 0x7f060008
			public const int one = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int relativeLayout = 2131099655;
			
			// aapt resource value: 0x7f06000e
			public const int seven = 2131099662;
			
			// aapt resource value: 0x7f060018
			public const int seventeen = 2131099672;
			
			// aapt resource value: 0x7f06000d
			public const int six = 2131099661;
			
			// aapt resource value: 0x7f060017
			public const int sixteen = 2131099671;
			
			// aapt resource value: 0x7f060045
			public const int sixty = 2131099717;
			
			// aapt resource value: 0x7f060040
			public const int sixtyone = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int sixtytwo = 2131099713;
			
			// aapt resource value: 0x7f060001
			public const int smileyFace = 2131099649;
			
			// aapt resource value: 0x7f060011
			public const int ten = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int thirteen = 2131099668;
			
			// aapt resource value: 0x7f060025
			public const int thirty = 2131099685;
			
			// aapt resource value: 0x7f06002d
			public const int thirtyeight = 2131099693;
			
			// aapt resource value: 0x7f06002a
			public const int thirtyfive = 2131099690;
			
			// aapt resource value: 0x7f060029
			public const int thirtyfour = 2131099689;
			
			// aapt resource value: 0x7f06002e
			public const int thirtynine = 2131099694;
			
			// aapt resource value: 0x7f060026
			public const int thirtyone = 2131099686;
			
			// aapt resource value: 0x7f06002c
			public const int thirtyseven = 2131099692;
			
			// aapt resource value: 0x7f06002b
			public const int thirtysix = 2131099691;
			
			// aapt resource value: 0x7f060028
			public const int thirtythree = 2131099688;
			
			// aapt resource value: 0x7f060027
			public const int thirtytwo = 2131099687;
			
			// aapt resource value: 0x7f06000a
			public const int three = 2131099658;
			
			// aapt resource value: 0x7f060013
			public const int twelve = 2131099667;
			
			// aapt resource value: 0x7f06001b
			public const int twenty = 2131099675;
			
			// aapt resource value: 0x7f060023
			public const int twentyeight = 2131099683;
			
			// aapt resource value: 0x7f060020
			public const int twentyfive = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int twentyfour = 2131099679;
			
			// aapt resource value: 0x7f060024
			public const int twentynine = 2131099684;
			
			// aapt resource value: 0x7f06001c
			public const int twentyone = 2131099676;
			
			// aapt resource value: 0x7f060022
			public const int twentyseven = 2131099682;
			
			// aapt resource value: 0x7f060021
			public const int twentysix = 2131099681;
			
			// aapt resource value: 0x7f06001e
			public const int twentythree = 2131099678;
			
			// aapt resource value: 0x7f06001d
			public const int twentytwo = 2131099677;
			
			// aapt resource value: 0x7f060009
			public const int two = 2131099657;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CheckerBoardGridView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MinnesotaZooListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MinnesotaZooListViewLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SmileyFace = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
